#!/bin/bash
for  disk  in `ls  /dev/sd*  |grep  -v  sdy`;
    do
     mkfs.xfs  -f  $disk
     if [ $? ne  0 ];then  
       echo  "$disk 格式化失败!"
      else
       echo  "$disk 格式化完成!" 
     fi 
     done
